[metadata.heroku]
  go-version = "1.10.7"
  root-package = "github.com/republicprotocol/renex-ingress-go"
  install = "./cmd/ingress"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.17"

[[constraint]]
  name = "github.com/republicprotocol/republic-go"
  branch = "new-settlement"

[[constraint]]
  name = "github.com/republicprotocol/swapperd"
  branch = "tests"

# Temporary fix https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
